#exec awesome
dropbox start &
xxkb &
setxkbmap -layout us,ru -variant -option grp:alt_shift_toggle,terminate:ctrl_alt_bksp &
conky --config=/home/vladimir/.conky/Makarov_Conky/Minimalistik_Panel & 
conky --config=/home/vladimir/.conky/Makarov_Conky/Clock & 
exec i3
